-- Add more work types: categories (Student, Employed, Unemployed, Others) and jobs (Handyman, Artisan, etc.)
insert into public.occupations (name) values
  ('Student'),
  ('Employed'),
  ('Unemployed'),
  ('Others'),
  ('Handyman'),
  ('Artisan'),
  ('Craftsman'),
  ('Technician'),
  ('Welder'),
  ('Painter'),
  ('Gardener'),
  ('Cleaner'),
  ('Caregiver'),
  ('Nanny'),
  ('Tutor'),
  ('Tailor'),
  ('Landscaper'),
  ('Housekeeper'),
  ('Babysitter'),
  ('Retail Worker'),
  ('Waiter'),
  ('Waitress'),
  ('Delivery Driver'),
  ('Security Guard'),
  ('Janitor'),
  ('Cook'),
  ('Factory Worker'),
  ('Construction Worker'),
  ('HVAC Technician'),
  ('Auto Mechanic'),
  ('Sewing Machinist'),
  ('Blacksmith'),
  ('Potter'),
  ('Jeweler'),
  ('Florist'),
  ('Baker'),
  ('Butcher'),
  ('Fisher'),
  ('Miner'),
  ('Driver'),
  ('Pilot'),
  ('Flight Attendant'),
  ('Sailor'),
  ('Soldier'),
  ('Veteran'),
  ('Retired'),
  ('Homemaker'),
  ('Self-Employed'),
  ('Contractor'),
  ('Intern'),
  ('Trainee'),
  ('Apprentice')
on conflict (name) do nothing;
